title: Taxonomy As A Service
description: Controlled Vocabularies and Taxonomies for Humanitarians
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://vocabulary.unocha.org' # the base hostname & protocol for your site, e.g. http://example.com
email: ocha-vocabulary@un.org

collections:
  - vocabs

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - Gruntfile.js
  - css/styles.scss
